---

AWSTemplateFormatVersion: '2010-09-09'
Description: SNS setup

Parameters:
  NotificationEmailAddress:
    Description: Email address to send alerts to
    Type: String
    Default: ""

  FoundationStackName:
    Description: Foundation stack name
    Type: String

Conditions:
  EmailSpecified: !Not [ !Equals [ !Ref NotificationEmailAddress, "" ] ]

Resources:
  SnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Ref FoundationStackName

  EmailSubscription:
    Type: "AWS::SNS::Subscription"
    Condition: EmailSpecified
    Properties:
      Endpoint: !Ref NotificationEmailAddress
      Protocol: email
      TopicArn: !Ref SnsTopic

Outputs:
  SnsTopic:
    Description: SNS Topic
    Export:
      Name: !Sub "${FoundationStackName}--SNS--Topic"
    Value:
      Ref: SnsTopic
